CREATE TABLE KLIENCI (
    ID_KLIENTA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    IMIE VARCHAR2(50) NOT NULL,
    NAZWISKO VARCHAR2(50) NOT NULL,
    TELEFON VARCHAR2(15) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE POJAZDY (
    ID_POJAZDU NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_KLIENTA NUMBER NOT NULL,
    MARKA VARCHAR2(50) NOT NULL,
    MODEL VARCHAR2(50) NOT NULL,
    ROK_PRODUKCJI NUMBER NOT NULL,
    NUMER_REJESTRACYJNY VARCHAR2(20) UNIQUE NOT NULL,
    FOREIGN KEY (ID_KLIENTA) REFERENCES KLIENCI(ID_KLIENTA) ON DELETE CASCADE
);

CREATE TABLE ZLECENIA (
    ID_ZLECENIA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_POJAZDU NUMBER NOT NULL,
    DATA_PRZYJECIA DATE DEFAULT SYSDATE NOT NULL,
    OPIS_PROBLEMU CLOB NOT NULL,
    STATUS VARCHAR2(20) CHECK (STATUS IN ('Oczekuje', 'W trakcie', 'Zakończone')) NOT NULL,
    FOREIGN KEY (ID_POJAZDU) REFERENCES POJAZDY(ID_POJAZDU) ON DELETE CASCADE
);


CREATE OR REPLACE TRIGGER SPRAWDZ_ROK_PRODUKCJI
BEFORE INSERT OR UPDATE ON POJAZDY
FOR EACH ROW
BEGIN
    IF :NEW.ROK_PRODUKCJI < 1900 OR :NEW.ROK_PRODUKCJI > EXTRACT(YEAR FROM SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20001, 'Niepoprawny rok produkcji!');
    END IF;
END;
/
