-- ============================================================================
-- SCHEMAT BAZY DANYCH CRM - System Wspomagania Warsztatu Samochodowego
-- Data: 2026-01-21
-- Wersja: 2.0 (rozszerzenie o funkcjonalności CRM)
-- ============================================================================

-- ============================================================================
-- 1. TABELE SŁOWNIKOWE (DICTIONARY TABLES)
-- Zawierają kody referencyjne używane w całym systemie
-- Każda tabela ma unikalny indeks na CODE
-- ============================================================================

-- Status użytkownika
CREATE TABLE DICT_USER_STATUS (
    CODE VARCHAR2(20) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500)
);

CREATE UNIQUE INDEX IDX_USER_STATUS_CODE ON DICT_USER_STATUS(CODE);

-- Role użytkowników (RBAC)
CREATE TABLE DICT_USER_ROLE (
    CODE VARCHAR2(20) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    PERMISSIONS VARCHAR2(1000) -- JSON lub lista uprawnień
);

CREATE UNIQUE INDEX IDX_USER_ROLE_CODE ON DICT_USER_ROLE(CODE);

-- Źródła leadów
CREATE TABLE DICT_LEAD_SOURCE (
    CODE VARCHAR2(20) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500)
);

CREATE UNIQUE INDEX IDX_LEAD_SOURCE_CODE ON DICT_LEAD_SOURCE(CODE);

-- Statusy leadów
CREATE TABLE DICT_LEAD_STATUS (
    CODE VARCHAR2(20) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    DISPLAY_ORDER NUMBER DEFAULT 0
);

CREATE UNIQUE INDEX IDX_LEAD_STATUS_CODE ON DICT_LEAD_STATUS(CODE);

-- Etapy pipeline (szans sprzedaży)
CREATE TABLE DICT_OPPORTUNITY_STAGE (
    CODE VARCHAR2(20) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    PROBABILITY NUMBER(5,2) DEFAULT 0, -- Prawdopodobieństwo zamknięcia (0-100%)
    DISPLAY_ORDER NUMBER DEFAULT 0,
    IS_CLOSED VARCHAR2(1) DEFAULT 'N' CHECK (IS_CLOSED IN ('Y', 'N'))
);

CREATE UNIQUE INDEX IDX_OPP_STAGE_CODE ON DICT_OPPORTUNITY_STAGE(CODE);

-- Typy aktywności
CREATE TABLE DICT_ACTIVITY_TYPE (
    CODE VARCHAR2(20) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    ICON VARCHAR2(50) -- Ikona w UI
);

CREATE UNIQUE INDEX IDX_ACTIVITY_TYPE_CODE ON DICT_ACTIVITY_TYPE(CODE);

-- Statusy aktywności
CREATE TABLE DICT_ACTIVITY_STATUS (
    CODE VARCHAR2(20) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    IS_COMPLETED VARCHAR2(1) DEFAULT 'N' CHECK (IS_COMPLETED IN ('Y', 'N'))
);

CREATE UNIQUE INDEX IDX_ACTIVITY_STATUS_CODE ON DICT_ACTIVITY_STATUS(CODE);

-- Priorytety
CREATE TABLE DICT_PRIORITY (
    CODE VARCHAR2(20) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    LEVEL NUMBER DEFAULT 1 -- 1=Low, 2=Medium, 3=High, 4=Urgent
);

CREATE UNIQUE INDEX IDX_PRIORITY_CODE ON DICT_PRIORITY(CODE);

-- Status zlecenia (rozszerzony dla CRM)
CREATE TABLE DICT_ORDER_STATUS (
    CODE VARCHAR2(20) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    DISPLAY_ORDER NUMBER DEFAULT 0
);

CREATE UNIQUE INDEX IDX_ORDER_STATUS_CODE ON DICT_ORDER_STATUS(CODE);

-- ============================================================================
-- 2. UŻYTKOWNICY I RBAC
-- ============================================================================

CREATE TABLE USERS (
    ID_USER NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    ROLE_CODE VARCHAR2(20) NOT NULL,
    STATUS_CODE VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_LOGIN TIMESTAMP,
    CONSTRAINT FK_USER_ROLE FOREIGN KEY (ROLE_CODE) REFERENCES DICT_USER_ROLE(CODE),
    CONSTRAINT FK_USER_STATUS FOREIGN KEY (STATUS_CODE) REFERENCES DICT_USER_STATUS(CODE)
);

-- Indeksy dla USERS
CREATE INDEX IDX_USER_ROLE ON USERS(ROLE_CODE);
CREATE INDEX IDX_USER_STATUS ON USERS(STATUS_CODE);
CREATE INDEX IDX_USER_EMAIL ON USERS(EMAIL);

-- ============================================================================
-- 3. ACCOUNTS (FIRMY/KONTA) - opcjonalne
-- ============================================================================

CREATE TABLE ACCOUNTS (
    ID_ACCOUNT NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ACCOUNT_NAME VARCHAR2(200) NOT NULL,
    ACCOUNT_TYPE VARCHAR2(50), -- 'Company', 'Individual'
    INDUSTRY VARCHAR2(100),
    WEBSITE VARCHAR2(200),
    PHONE VARCHAR2(20),
    EMAIL VARCHAR2(100),
    BILLING_ADDRESS VARCHAR2(500),
    SHIPPING_ADDRESS VARCHAR2(500),
    DESCRIPTION CLOB,
    OWNER_ID NUMBER,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_ACCOUNT_OWNER FOREIGN KEY (OWNER_ID) REFERENCES USERS(ID_USER)
);

CREATE INDEX IDX_ACCOUNT_OWNER ON ACCOUNTS(OWNER_ID);
CREATE INDEX IDX_ACCOUNT_NAME ON ACCOUNTS(ACCOUNT_NAME);
CREATE INDEX IDX_ACCOUNT_TYPE ON ACCOUNTS(ACCOUNT_TYPE);

-- ============================================================================
-- 4. CONTACTS (KONTAKTY) - rozszerzenie z KLIENCI
-- ============================================================================

CREATE TABLE CONTACTS (
    ID_CONTACT NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ACCOUNT_ID NUMBER, -- Opcjonalny FK do ACCOUNTS
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    PHONE VARCHAR2(20),
    MOBILE VARCHAR2(20),
    TITLE VARCHAR2(100), -- Stanowisko
    DEPARTMENT VARCHAR2(100),
    ADDRESS VARCHAR2(500),
    DESCRIPTION CLOB,
    OWNER_ID NUMBER,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_CONTACT_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ID_ACCOUNT),
    CONSTRAINT FK_CONTACT_OWNER FOREIGN KEY (OWNER_ID) REFERENCES USERS(ID_USER)
);

-- Indeksy dla CONTACTS
CREATE INDEX IDX_CONTACT_ACCOUNT ON CONTACTS(ACCOUNT_ID);
CREATE INDEX IDX_CONTACT_OWNER ON CONTACTS(OWNER_ID);
CREATE INDEX IDX_CONTACT_EMAIL ON CONTACTS(EMAIL);
CREATE INDEX IDX_CONTACT_NAME ON CONTACTS(LAST_NAME, FIRST_NAME);

-- ============================================================================
-- 5. LEADS (LEADY)
-- ============================================================================

CREATE TABLE LEADS (
    ID_LEAD NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    COMPANY VARCHAR2(200),
    EMAIL VARCHAR2(100),
    PHONE VARCHAR2(20),
    TITLE VARCHAR2(100),
    SOURCE_CODE VARCHAR2(20) NOT NULL,
    STATUS_CODE VARCHAR2(20) NOT NULL,
    RATING VARCHAR2(20), -- Hot, Warm, Cold
    DESCRIPTION CLOB,
    OWNER_ID NUMBER,
    CONVERTED_TO_CONTACT_ID NUMBER,
    CONVERTED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_LEAD_SOURCE FOREIGN KEY (SOURCE_CODE) REFERENCES DICT_LEAD_SOURCE(CODE),
    CONSTRAINT FK_LEAD_STATUS FOREIGN KEY (STATUS_CODE) REFERENCES DICT_LEAD_STATUS(CODE),
    CONSTRAINT FK_LEAD_OWNER FOREIGN KEY (OWNER_ID) REFERENCES USERS(ID_USER),
    CONSTRAINT FK_LEAD_CONVERTED FOREIGN KEY (CONVERTED_TO_CONTACT_ID) REFERENCES CONTACTS(ID_CONTACT)
);

-- Indeksy dla LEADS
CREATE INDEX IDX_LEAD_SOURCE ON LEADS(SOURCE_CODE);
CREATE INDEX IDX_LEAD_STATUS ON LEADS(STATUS_CODE);
CREATE INDEX IDX_LEAD_OWNER ON LEADS(OWNER_ID);
CREATE INDEX IDX_LEAD_RATING ON LEADS(RATING);
CREATE INDEX IDX_LEAD_OWNER_STATUS ON LEADS(OWNER_ID, STATUS_CODE);
CREATE INDEX IDX_LEAD_CREATED ON LEADS(CREATED_AT DESC);

-- ============================================================================
-- 6. OPPORTUNITIES (SZANSE SPRZEDAŻY / PIPELINE)
-- ============================================================================

CREATE TABLE OPPORTUNITIES (
    ID_OPPORTUNITY NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    OPPORTUNITY_NAME VARCHAR2(200) NOT NULL,
    ACCOUNT_ID NUMBER,
    CONTACT_ID NUMBER,
    STAGE_CODE VARCHAR2(20) NOT NULL,
    AMOUNT NUMBER(15,2),
    PROBABILITY NUMBER(5,2), -- 0-100%
    EXPECTED_CLOSE_DATE DATE,
    ACTUAL_CLOSE_DATE DATE,
    DESCRIPTION CLOB,
    NEXT_STEP VARCHAR2(500),
    OWNER_ID NUMBER,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_OPP_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ID_ACCOUNT),
    CONSTRAINT FK_OPP_CONTACT FOREIGN KEY (CONTACT_ID) REFERENCES CONTACTS(ID_CONTACT),
    CONSTRAINT FK_OPP_STAGE FOREIGN KEY (STAGE_CODE) REFERENCES DICT_OPPORTUNITY_STAGE(CODE),
    CONSTRAINT FK_OPP_OWNER FOREIGN KEY (OWNER_ID) REFERENCES USERS(ID_USER)
);

-- Indeksy dla OPPORTUNITIES - złożone dla typowych zapytań
CREATE INDEX IDX_OPP_ACCOUNT ON OPPORTUNITIES(ACCOUNT_ID);
CREATE INDEX IDX_OPP_CONTACT ON OPPORTUNITIES(CONTACT_ID);
CREATE INDEX IDX_OPP_STAGE ON OPPORTUNITIES(STAGE_CODE);
CREATE INDEX IDX_OPP_OWNER ON OPPORTUNITIES(OWNER_ID);
CREATE INDEX IDX_OPP_OWNER_STAGE ON OPPORTUNITIES(OWNER_ID, STAGE_CODE);
CREATE INDEX IDX_OPP_CLOSE_DATE ON OPPORTUNITIES(EXPECTED_CLOSE_DATE);
CREATE INDEX IDX_OPP_CREATED ON OPPORTUNITIES(CREATED_AT DESC);

-- ============================================================================
-- 7. ACTIVITIES (AKTYWNOŚCI: TASK, MEETING, CALL, EMAIL)
-- ============================================================================

CREATE TABLE ACTIVITIES (
    ID_ACTIVITY NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SUBJECT VARCHAR2(200) NOT NULL,
    TYPE_CODE VARCHAR2(20) NOT NULL,
    STATUS_CODE VARCHAR2(20) NOT NULL,
    PRIORITY_CODE VARCHAR2(20) DEFAULT 'MEDIUM',
    DESCRIPTION CLOB,
    DUE_DATE TIMESTAMP,
    COMPLETED_AT TIMESTAMP,
    DURATION_MINUTES NUMBER, -- dla meeting/call
    LOCATION VARCHAR2(200), -- dla meeting
    -- Relacje polimorficzne
    RELATED_TO_TYPE VARCHAR2(50), -- 'Lead', 'Contact', 'Account', 'Opportunity'
    RELATED_TO_ID NUMBER,
    OWNER_ID NUMBER,
    ASSIGNED_TO_ID NUMBER,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_ACTIVITY_TYPE FOREIGN KEY (TYPE_CODE) REFERENCES DICT_ACTIVITY_TYPE(CODE),
    CONSTRAINT FK_ACTIVITY_STATUS FOREIGN KEY (STATUS_CODE) REFERENCES DICT_ACTIVITY_STATUS(CODE),
    CONSTRAINT FK_ACTIVITY_PRIORITY FOREIGN KEY (PRIORITY_CODE) REFERENCES DICT_PRIORITY(CODE),
    CONSTRAINT FK_ACTIVITY_OWNER FOREIGN KEY (OWNER_ID) REFERENCES USERS(ID_USER),
    CONSTRAINT FK_ACTIVITY_ASSIGNED FOREIGN KEY (ASSIGNED_TO_ID) REFERENCES USERS(ID_USER)
);

-- Indeksy dla ACTIVITIES - złożone dla typowych list
CREATE INDEX IDX_ACTIVITY_TYPE ON ACTIVITIES(TYPE_CODE);
CREATE INDEX IDX_ACTIVITY_STATUS ON ACTIVITIES(STATUS_CODE);
CREATE INDEX IDX_ACTIVITY_PRIORITY ON ACTIVITIES(PRIORITY_CODE);
CREATE INDEX IDX_ACTIVITY_OWNER ON ACTIVITIES(OWNER_ID);
CREATE INDEX IDX_ACTIVITY_ASSIGNED ON ACTIVITIES(ASSIGNED_TO_ID);
CREATE INDEX IDX_ACTIVITY_RELATED ON ACTIVITIES(RELATED_TO_TYPE, RELATED_TO_ID);
CREATE INDEX IDX_ACTIVITY_OWNER_STATUS_DUE ON ACTIVITIES(OWNER_ID, STATUS_CODE, DUE_DATE);
CREATE INDEX IDX_ACTIVITY_DUE ON ACTIVITIES(DUE_DATE);

-- ============================================================================
-- 8. NOTES (NOTATKI)
-- ============================================================================

CREATE TABLE NOTES (
    ID_NOTE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR2(200),
    CONTENT CLOB NOT NULL,
    -- Relacje polimorficzne
    RELATED_TO_TYPE VARCHAR2(50), -- 'Lead', 'Contact', 'Account', 'Opportunity'
    RELATED_TO_ID NUMBER,
    CREATED_BY NUMBER,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_NOTE_CREATOR FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID_USER)
);

CREATE INDEX IDX_NOTE_RELATED ON NOTES(RELATED_TO_TYPE, RELATED_TO_ID);
CREATE INDEX IDX_NOTE_CREATOR ON NOTES(CREATED_BY);
CREATE INDEX IDX_NOTE_CREATED ON NOTES(CREATED_AT DESC);

-- ============================================================================
-- 9. ATTACHMENTS (ZAŁĄCZNIKI)
-- ============================================================================

CREATE TABLE ATTACHMENTS (
    ID_ATTACHMENT NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FILE_NAME VARCHAR2(255) NOT NULL,
    FILE_PATH VARCHAR2(500) NOT NULL,
    FILE_TYPE VARCHAR2(100),
    FILE_SIZE NUMBER,
    -- Relacje polimorficzne
    RELATED_TO_TYPE VARCHAR2(50), -- 'Lead', 'Contact', 'Account', 'Opportunity', 'Activity'
    RELATED_TO_ID NUMBER,
    UPLOADED_BY NUMBER,
    UPLOADED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ATTACHMENT_UPLOADER FOREIGN KEY (UPLOADED_BY) REFERENCES USERS(ID_USER)
);

CREATE INDEX IDX_ATTACHMENT_RELATED ON ATTACHMENTS(RELATED_TO_TYPE, RELATED_TO_ID);
CREATE INDEX IDX_ATTACHMENT_UPLOADER ON ATTACHMENTS(UPLOADED_BY);

-- ============================================================================
-- 10. INTEGRACJA Z ISTNIEJĄCYMI TABELAMI WARSZTATOWYMI
-- Zachowanie istniejącej struktury jako moduł "Serwis"
-- ============================================================================

-- KLIENCI - pozostaje bez zmian, ale można dodać relację do CONTACTS
CREATE TABLE KLIENCI (
    ID_KLIENTA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    IMIE VARCHAR2(50) NOT NULL,
    NAZWISKO VARCHAR2(50) NOT NULL,
    TELEFON VARCHAR2(15) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    CONTACT_ID NUMBER, -- Opcjonalna relacja do CRM CONTACTS
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_KLIENT_CONTACT FOREIGN KEY (CONTACT_ID) REFERENCES CONTACTS(ID_CONTACT)
);

CREATE INDEX IDX_KLIENT_CONTACT ON KLIENCI(CONTACT_ID);

-- POJAZDY - pozostaje bez zmian
CREATE TABLE POJAZDY (
    ID_POJAZDU NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_KLIENTA NUMBER NOT NULL,
    MARKA VARCHAR2(50) NOT NULL,
    MODEL VARCHAR2(50) NOT NULL,
    ROK_PRODUKCJI NUMBER NOT NULL,
    NUMER_REJESTRACYJNY VARCHAR2(20) UNIQUE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    FOREIGN KEY (ID_KLIENTA) REFERENCES KLIENCI(ID_KLIENTA) ON DELETE CASCADE
);

CREATE INDEX IDX_POJAZD_KLIENT ON POJAZDY(ID_KLIENTA);

-- ZLECENIA - rozszerzone o status_code i owner
CREATE TABLE ZLECENIA (
    ID_ZLECENIA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_POJAZDU NUMBER NOT NULL,
    DATA_PRZYJECIA DATE DEFAULT SYSDATE NOT NULL,
    OPIS_PROBLEMU CLOB NOT NULL,
    STATUS VARCHAR2(20) CHECK (STATUS IN ('Oczekuje', 'W trakcie', 'Zakończone')) NOT NULL,
    STATUS_CODE VARCHAR2(20), -- Nowy FK do słownika
    OWNER_ID NUMBER,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    FOREIGN KEY (ID_POJAZDU) REFERENCES POJAZDY(ID_POJAZDU) ON DELETE CASCADE,
    CONSTRAINT FK_ZLECENIE_STATUS FOREIGN KEY (STATUS_CODE) REFERENCES DICT_ORDER_STATUS(CODE),
    CONSTRAINT FK_ZLECENIE_OWNER FOREIGN KEY (OWNER_ID) REFERENCES USERS(ID_USER)
);

CREATE INDEX IDX_ZLECENIE_POJAZD ON ZLECENIA(ID_POJAZDU);
CREATE INDEX IDX_ZLECENIE_STATUS ON ZLECENIA(STATUS_CODE);
CREATE INDEX IDX_ZLECENIE_OWNER ON ZLECENIA(OWNER_ID);

-- Trigger dla POJAZDY (z oryginalnego skryptu)
CREATE OR REPLACE TRIGGER SPRAWDZ_ROK_PRODUKCJI
BEFORE INSERT OR UPDATE ON POJAZDY
FOR EACH ROW
BEGIN
    IF :NEW.ROK_PRODUKCJI < 1900 OR :NEW.ROK_PRODUKCJI > EXTRACT(YEAR FROM SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20001, 'Niepoprawny rok produkcji!');
    END IF;
END;
/

-- ============================================================================
-- KONIEC SCHEMATU
-- ============================================================================
